"""create new rentals table

Revision ID: 15429b930c04
Revises: ef0bc92f53be
Create Date: 2024-07-25 22:06:17.537959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15429b930c04'
down_revision: Union[str, None] = 'ef0bc92f53be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rentals', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rentals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_column('rentals', 'vehicle_id')
    op.drop_column('rentals', 'user_id')
    # ### end Alembic commands ###
