"""edited customers table

Revision ID: 1613176a395a
Revises: b7e2c2291bd5
Create Date: 2024-07-23 16:02:48.873246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1613176a395a'
down_revision: Union[str, None] = 'b7e2c2291bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'created_by')
    # ### end Alembic commands ###
