"""Added unique to vehicle number plate

Revision ID: 43bf29f8de26
Revises: 6351cbcce466
Create Date: 2024-07-29 17:08:41.715761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bf29f8de26'
down_revision: Union[str, None] = '6351cbcce466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['numberplate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
