"""Set vehicle to unique

Revision ID: 469f0ea12552
Revises: b8d788690bfa
Create Date: 2025-01-03 22:53:15.321527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469f0ea12552'
down_revision: Union[str, None] = 'b8d788690bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rentals', ['vehicle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='unique')
    # ### end Alembic commands ###
