"""Added calendar color to rental table

Revision ID: 5ed98a594e5e
Revises: e25a7cd4777b
Create Date: 2024-07-29 13:15:24.789125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed98a594e5e'
down_revision: Union[str, None] = 'e25a7cd4777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('calendar_color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'calendar_color')
    # ### end Alembic commands ###
