"""Added unique to vehicle number plate

Revision ID: 6351cbcce466
Revises: 9b2a6e34e90b
Create Date: 2024-07-29 17:03:38.050865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6351cbcce466'
down_revision: Union[str, None] = '9b2a6e34e90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
