"""Add start and end date to rentals table

Revision ID: 641ff384bdb1
Revises: 688a4dc78f29
Create Date: 2024-07-26 00:49:15.443845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641ff384bdb1'
down_revision: Union[str, None] = '688a4dc78f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('rentals', sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'end_date')
    op.drop_column('rentals', 'start_date')
    # ### end Alembic commands ###
