"""Added owner info to sales

Revision ID: 84e3afe456f9
Revises: 10828abf3d81
Create Date: 2024-07-29 16:10:57.903036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e3afe456f9'
down_revision: Union[str, None] = '10828abf3d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'owner_id')
    # ### end Alembic commands ###
