"""Added id to rentals table

Revision ID: 9b2a6e34e90b
Revises: 84e3afe456f9
Create Date: 2024-07-29 16:59:18.606096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2a6e34e90b'
down_revision: Union[str, None] = '84e3afe456f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'id')
    # ### end Alembic commands ###
