"""Create blank rental table

Revision ID: c6f4f8b92487
Revises: ec9a3ae75df3
Create Date: 2025-01-03 22:59:18.004042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f4f8b92487'
down_revision: Union[str, None] = 'ec9a3ae75df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
