"""Added rest of table

Revision ID: caf736800a1d
Revises: 97b74fd35a77
Create Date: 2025-01-03 23:02:13.982441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf736800a1d'
down_revision: Union[str, None] = '97b74fd35a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('rentals', sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('rentals', sa.Column('calendar_color', sa.String(), nullable=False))
    op.add_column('rentals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    op.create_unique_constraint(None, 'rentals', ['vehicle_id'])
    op.create_foreign_key(None, 'rentals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rentals', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rentals', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='unique')
    op.drop_column('rentals', 'created_at')
    op.drop_column('rentals', 'customer_id')
    op.drop_column('rentals', 'vehicle_id')
    op.drop_column('rentals', 'user_id')
    op.drop_column('rentals', 'calendar_color')
    op.drop_column('rentals', 'end_date')
    op.drop_column('rentals', 'start_date')
    # ### end Alembic commands ###
