"""Added default values to start + end date for testing

Revision ID: e25a7cd4777b
Revises: 641ff384bdb1
Create Date: 2024-07-26 00:57:25.050292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25a7cd4777b'
down_revision: Union[str, None] = '641ff384bdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
