"""Added customer id to Rental table

Revision ID: ef0bc92f53be
Revises: b9682f6027a8
Create Date: 2024-07-25 21:58:02.051739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0bc92f53be'
down_revision: Union[str, None] = 'b9682f6027a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rentals', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_column('rentals', 'customer_id')
    # ### end Alembic commands ###
